{
 "title": "NAP Processing Overview",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "lcp",
    "query": "{\"find\": \"terms\", \"field\": \"payload.lcp\", \"size\": 2}"
   },
   {
    "name": "merchant",
    "query": "Google : 27d2aadb-c444-4788-9195-5a42715a1d13, Tesco : 861edc23-ae0e-4a1d-84c8-c6aa98fb284e"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "occurred_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "payload.value",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "sum"
      },
      { "field": "payload.schemeFeeAmount", "id": "3", "type": "sum" },
      { "field": "payload.interchangeCostAmount", "id": "4", "type": "sum" }
     ],
     "query": "name : \"payment_cleared\" AND payload.lcp : $lcp AND payload.merchantId : $merchant",
     "timeField": "occurred_at"
    },
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "occurred_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "payload.chargesAmount", "id": "1", "type": "sum" }
     ],
     "query": "name : \"payment_charge_calculated\" AND payload.lcp : $lcp AND payload.merchantId : $merchant",
     "timeField": "occurred_at"
    }
   ]
  },
  {
   "title": "Flow",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "paid_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "lcp : $lcp",
     "timeField": "paid_at"
    },
    {
     "bucketAggs": [
      { "field": "occurred_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "name : \"payment_cleared\" AND payload.lcp : $lcp AND payload.merchantId: $merchant",
     "timeField": "occurred_at"
    },
    {
     "bucketAggs": [
      { "field": "occurred_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "name : \"payment_charge_calculated\" AND payload.lcp : $lcp AND payload.merchantId: $merchant",
     "timeField": "occurred_at"
    },
    {
     "bucketAggs": [
      { "field": "occurred_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "name : \"payment_charge_calculation_failed\" AND payload.merchantId: $merchant",
     "timeField": "occurred_at"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "category : event AND payload.lcp : $lcp AND payload.merchantId : $merchant",
     "timeField": "occurred_at"
    }
   ]
  }
 ]
}